import os
import sys
import argparse
import json
import pickle
import numpy as np
import tensorflow as tf

from . import config


# ─────────────────────────────────────────────────────────────
# ARGUMENT PARSER
# ─────────────────────────────────────────────────────────────
def parse_args():
    p = argparse.ArgumentParser(description="Convert model → TFLite INT8")
    p.add_argument("--model", choices=["tomato", "potato"],
                   default="tomato", help="Which model to convert")
    p.add_argument("--no-verify", action="store_true",
                   help="Skip accuracy verification (faster)")
    p.add_argument("--full-int8", action="store_true",
                   help="Full INT8 (input+output too). Default: hybrid.")
    return p.parse_args()


# ─────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────
def get_paths(model_name):
    if model_name == "tomato":
        return {
            "keras":   config.TOMATO_MODEL_H5,
            "meta":    config.TOMATO_MODEL_META,
            "splits":  config.TOMATO_SPLITS_FILE,
            "tflite":  config.TOMATO_MODEL_TFLITE,
            "header":  config.TOMATO_MODEL_TFLITE.replace(".tflite", ".h"),
        }
    return {
        "keras":   config.POTATO_MODEL_H5,
        "meta":    config.POTATO_MODEL_META,
        "splits":  config.POTATO_SPLITS_FILE,
        "tflite":  config.POTATO_MODEL_TFLITE,
        "header":  config.POTATO_MODEL_TFLITE.replace(".tflite", ".h"),
    }


def representative_dataset(splits_path, num_samples=200):

    with open(splits_path, "rb") as f:
        splits = pickle.load(f)

    X = splits["X_train"][:num_samples].astype("float32")

    def gen():
        for i in range(len(X)):
            yield [np.expand_dims(X[i], axis=0)]

    return gen


def convert_to_tflite(keras_path, splits_path, full_int8=False):
   
    print(f" Loading Keras model: {keras_path}")
    model = tf.keras.models.load_model(keras_path)

    print(f" Converting to TFLite (INT8 quantization)...")
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset(splits_path)

    if full_int8:
        # Full INT8: model I/O also quantized. Smallest model.
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.uint8
        converter.inference_output_type = tf.uint8
        print("   Mode: FULL INT8 (input/output quantized)")
    else:
        # Hybrid: weights INT8, I/O float32. Slightly larger, easier to use.
        converter.target_spec.supported_ops = [
            tf.lite.OpsSet.TFLITE_BUILTINS,
            tf.lite.OpsSet.SELECT_TF_OPS,
        ]
        print("   Mode: HYBRID (weights INT8, I/O float32)")

    tflite_model = converter.convert()
    return tflite_model


def verify_tflite(tflite_path, splits_path, class_display):
    """Compare TFLite vs Keras accuracy on the test set."""
    print("\n" + "=" * 60)
    print("VERIFYING TFLITE ACCURACY")
    print("=" * 60)

    with open(splits_path, "rb") as f:
        splits = pickle.load(f)

    X_test = splits["X_test"].astype("float32")
    y_test = splits["y_test"]

    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    in_dtype = input_details[0]["dtype"]
    out_dtype = output_details[0]["dtype"]
    print(f"   Input:  {input_details[0]['shape']} ({in_dtype.__name__})")
    print(f"   Output: {output_details[0]['shape']} ({out_dtype.__name__})")

    correct = 0
    for i in range(len(X_test)):
        img = X_test[i:i+1]
        # Handle full-int8 quantized I/O
        if in_dtype == np.uint8:
            img = img.astype("uint8")

        interpreter.set_tensor(input_details[0]["index"], img)
        interpreter.invoke()
        out = interpreter.get_tensor(output_details[0]["index"])[0]

        if out_dtype == np.uint8:
            pred = int(np.argmax(out))
        else:
            pred = int(np.argmax(out))

        if pred == y_test[i]:
            correct += 1

    acc = correct / len(X_test)
    print(f"\n TFLite test accuracy: {acc:.4f}")
    return acc


def export_to_c_header(tflite_bytes, header_path, var_name="tomato_model"):
    """Convert .tflite bytes to a C header array for ESP32 firmware."""
    print(f"\n Writing C header: {header_path}")

    lines = [
        "// Auto-generated by src/convert_tflite.py — DO NOT EDIT",
        f"// Size: {len(tflite_bytes)} bytes ({len(tflite_bytes)/1024:.1f} KB)",
        "",
        "#ifndef MODEL_H",
        "#define MODEL_H",
        "",
        "#include <stdint.h>",
        "",
        f"const unsigned char {var_name}[] = {{",
    ]

    # 12 bytes per line for readability
    for i in range(0, len(tflite_bytes), 12):
        chunk = tflite_bytes[i:i+12]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hexes},")

    lines += [
        "};",
        "",
        f"const unsigned int {var_name}_len = {len(tflite_bytes)};",
        "",
        "#endif  // MODEL_H",
        "",
    ]

    with open(header_path, "w") as f:
        f.write("\n".join(lines))

    print(f"   Size: {len(tflite_bytes)/1024:.1f} KB")


# ─────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────
def main():
    args = parse_args()
    paths = get_paths(args.model)

    print("=" * 60)
    print(f"TFLITE CONVERSION — {args.model.upper()}")
    print("=" * 60)
    print(f"   Keras:  {paths['keras']}")
    print(f"   TFLite: {paths['tflite']}")
    print(f"   Header: {paths['header']}")

    # Convert
    tflite_bytes = convert_to_tflite(
        paths["keras"], paths["splits"], args.full_int8
    )

    size_kb = len(tflite_bytes) / 1024
    print(f"\n TFLite model: {size_kb:.1f} KB")

    # Save .tflite
    os.makedirs(os.path.dirname(paths["tflite"]), exist_ok=True)
    with open(paths["tflite"], "wb") as f:
        f.write(tflite_bytes)
    print(f" Saved: {paths['tflite']}")

    # Save C header
    var_name = f"{args.model}_model"
    export_to_c_header(tflite_bytes, paths["header"], var_name)

    # Verify
    if not args.no_verify:
        acc = verify_tflite(
            paths["tflite"], paths["splits"],
            class_display=getattr(config, f"{args.model.upper()}_CLASS_DISPLAY",
                                  {})
        )

    # Size warning
    print("\n" + "=" * 60)
    print("SIZE ANALYSIS")
    print("=" * 60)
    if size_kb < 250:
        print(" Model fits comfortably in ESP32 flash")
    elif size_kb < 500:
        print("  Model is getting large. Consider loading from SD card.")
    elif size_kb < 1500:
        print("  Model > 500KB. Must load from SD card into PSRAM.")
    else:
        print(" Model too large. Retrain with smaller backbone "
              "(MobileNetV3-Small) or reduce input to 64×64.")

    print(f"\n Output files:")
    print(f"   {paths['tflite']}")
    print(f"   {paths['header']}")


if __name__ == "__main__":
    main()